//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLLAgroFLor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbAgroFlorEntities : DbContext
    {
        public dbAgroFlorEntities()
            : base("name=dbAgroFlorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<config> config { get; set; }
        public virtual DbSet<floricola> floricola { get; set; }
        public virtual DbSet<registro> registro { get; set; }
        public virtual DbSet<variedades> variedades { get; set; }
    }
}
